export const GET_TEAM_INFO_REQUEST = 'GET_TEAM_INFO_REQUEST';
export const GET_TEAM_INFO_SUCCESS = 'GET_TEAM_INFO_SUCCESS';
export const GET_TEAM_INFO_FAILURE = 'GET_TEAM_INFO_FAILURE';

export const TWITCH_CHANNEL_REQUEST = 'TWITCH_CHANNEL_REQUEST';
export const TWITCH_CHANNEL_SUCCESS = 'TWITCH_CHANNEL_SUCCESS';
export const TWITCH_CHANNEL_FAILURE = 'TWITCH_CHANNEL_FAILURE';
