export const GET_TEAM_INFO_REQUEST = 'GET_TEAM_INFO_REQUEST';
export const GET_TEAM_INFO_SUCCESS = 'GET_TEAM_INFO_SUCCESS';
export const GET_TEAM_INFO_FAILURE = 'GET_TEAM_INFO_FAILURE';

export const GET_TEAM_ROSTER_REQUEST = 'GET_TEAM_ROSTER_REQUEST';
export const GET_TEAM_ROSTER_SUCCESS = 'GET_TEAM_ROSTER_SUCCESS';
export const GET_TEAM_ROSTER_FAILURE = 'GET_TEAM_ROSTER_FAILURE';

export const SET_TEAM_ID = 'SET_TEAM_ID';

export const TWITCH_USERS_REQUEST = 'TWITCH_USERS_REQUEST';
export const TWITCH_USERS_SUCCESS = 'TWITCH_USERS_SUCCESS';
export const TWITCH_USERS_FAILURE = 'TWITCH_USERS_FAILURE';

export const TWITCH_STREAMS_REQUEST = 'TWITCH_STREAMS_REQUEST';
export const TWITCH_STREAMS_SUCCESS = 'TWITCH_STREAMS_SUCCESS';
export const TWITCH_STREAMS_FAILURE = 'TWITCH_STREAMS_FAILURE';
